### ISSUE TITLE
Support minify

### ISSUE THREAD

**Issue by acrazing** [Igorbek/typescript-plugin-styled-components#14]
It's useful for production, just like babel plugin, see <https://github.com/styled-components/babel-plugin-styled-components/blob/master/src/minify/index.js>

**Comment by Igorbek** [comment]
Thank for the suggestion. I will explore this feature. From what I saw, it looks they do:
- strip inline and line comments out
- reduce raw and "cooked" version of strings passed in

**Comment by popbee** [comment]
+1 I would use this.  

Beware that trying to minify the CSS can be dangerous because the interpolation could happen anywhere within the syntax of the CSS. Even if they tried to be very careful, they saw that it is near-impossible to guarantee it will be OK in all possible cases. The net result is that babel plugin does not turn it on by default.

Related to minifying. If you look into the generated bundle, each styled-component template string is stored... *twice*!  Such a waste of bundle space. One of the transformation they do is to turn the template into a direct function call without knowing that only one of the `cooked` / `raw` values is actually used by styled-component.  (Note that the babel TS transpiler now has a new feature to only transpile a single copy of the string if they are equal, but I rather stay with the Typescript engine, which is the reason of this project).

https://github.com/styled-components/babel-plugin-styled-components/blob/master/src/visitors/templateLiterals/transpile.js

**Comment by Igorbek** [comment]
Thank you @popbee for additional insights.
I have to convince that I won't be able to work on this or any other feature in a next month since have vacation scheduled. If anyone wants to make a PR it will be very welcomed.
Anyways, I will start to work on this in mid September.

**Comment by jcampalo** [comment]
Any updates @Igorbek?

**Comment by Igorbek** [comment]
Ah, what a shame! I did start to work on that but din't have time to finish it yet.
The work in progress is in `minification` branch. All this week I'm on the Developer Week and won't be able to work. I'll try to get back to this next week. Hopefully should be done by end of February.
As always, any help will be appreciated and feel free to contribute.

**Comment by Igorbek** [comment]
The feature is ready to be merged #35
I am not sure that everything is covered, please see if it does do that right, here in tests: https://github.com/Igorbek/typescript-plugin-styled-components/tree/minification/src/__tests__/baselines/minification

**Comment by HoraceSupertramp** [comment]
Any news about this?

**Comment by Igorbek** [comment]
@HoraceSupertramp the feature has been implemented, not yet merged though.
I can create a preview release tomorrow so you can try it out. If everything is ok, it will be released as a full release after 1 week.

**Comment by HoraceSupertramp** [comment]
Fine for me! Can’t wait to integrate this within a JavaScript project of mine

**Comment by Igorbek** [comment]
[Version 1.4.0-rc](https://github.com/Igorbek/typescript-plugin-styled-components/releases/tag/1.4.0-rc) with minification support has been published. Any feedback will be much appreciated.
