### ISSUE TITLE
Bug report: some syntax cannot be transformed

### ISSUE THREAD

**Issue by acrazing** [Igorbek/typescript-plugin-styled-components#89]
1. in function return statement:
    ```ts
    export function inReturn() {
      return styled.div`
        content: "in return";
      `
    }
    ```

    transform result:

    ```ts
    function inReturn() {
        return styled_components_1.default.div `content:"in return";`;
    }
    exports.inReturn = inReturn;
    ```

2. wrapped by type cast:

    ```ts    
    export const Wrap = (styled.div as StyledFunction<FunctionComponent<Props>>)`
      content: ${props => props.content};
    `;
    
    export const WrapAll = (styled.div`
      content: "wrap all";
    `) as unknown as StyledFunction<FunctionComponent<Props>>;
   ```

    transform result:

    ```ts
    exports.Wrap = styled_components_1.default.div `
      content: ${props => props.content};
    `;
    exports.WrapAll = (styled_components_1.default.div `content:"wrap all";`);
    ```

**Comment by Igorbek** [comment]
@acrazing thank you for the request.
It seems to be more of enhancement rather than a bug report.
I would like to clarify what is the expected result in these cases?

### Case 1

```ts
export function inReturn() {
  return styled.div`
    content: "in return";
  `
}
```

- should it give the name `inReturn`?
- what if the function is not pure?
  - should it only allow to have a single `return` statement?
    - why not to write `const InReturn = styled.div`...`; function inReturn { return InReturn }`?
  - how to determine the component is actually has to have the name of the function?

### Case 2

Here it is not easy to agree that the intent is the same having many other types users can cast to.
We can actually drop this no-op type casting when detecting styled components... let me think of it.

Please let me know what you think about it especially case 1.

**Comment by acrazing** [comment]
It's too late to talking about this issue, I've written a replacement to support my project, you can see it at [acrazing/typescript-styled-components-plugin](https://github.com/acrazing/typescript-styled-components-plugin).

Any way, **case 1** has nothing to do with side effects and `displayName`, we just want to add `componentId` for `SSR`, this case also exists in other places, such as `export default styled.xxx`, `const foo = [styled.xxx, style.yyy]`, etc. **Case 2** has been solved in my repository, you can see it at https://github.com/acrazing/typescript-styled-components-plugin/blob/636d2eafe8/src/should.ts#L29-L35
